"""
/api/v1/market-state — Unified Market State endpoint.
Phase 1: reads market_state.json (generated by market_state_coordinator).
Phase 2: will also expose on-demand coordination.
"""

import json
import logging
import sys
from pathlib import Path

from fastapi import APIRouter

logger = logging.getLogger(__name__)

from src.core.canonical_output_adapter import localize_output

router = APIRouter()


def _hydrate_path():
    if getattr(sys, 'frozen', False):
        root_path = Path(sys.executable).resolve().parent
    else:
        current = Path(__file__).resolve().parent
        root_path = current
        while current != current.parent:
            if (current / "AGENTS.md").exists() and (current / "backend").is_dir():
                root_path = current
                break
            current = current.parent
    if str(root_path) not in sys.path:
        sys.path.insert(0, str(root_path))
    return root_path


PROJECT_ROOT = _hydrate_path()
STATE_PATH = Path(str(PROJECT_ROOT)) / "backend" / "data" / "market_state.json"


def _load_state() -> dict:
    if not STATE_PATH.exists():
        return {"error": "market_state.json not found. Run market_state_coordinator first."}
    try:
        with open(STATE_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"Failed to read market_state.json: {e}")
        return {"error": str(e)}


@router.get("/", summary="Unified market state")
async def get_market_state():
    return localize_output(_load_state())


@router.get("/meta", summary="Meta state only")
async def get_meta_state():
    state = _load_state()
    if "meta_state" in state:
        return localize_output(state["meta_state"])
    return localize_output(state)


@router.get("/regime", summary="Regime + meta")
async def get_regime_context():
    state = _load_state()
    return localize_output({
        "regime": state.get("market_regime", {}),
        "meta": state.get("meta_state", {}),
        "timestamp": state.get("timestamp", ""),
    })
